name: Deploy Docusaurus to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}

      - name: Check build contents
        run: |
          echo "Listing build directory:"
          dir ${{ github.workspace }}/build

      - name: Deploy to IIS
        uses: ChristopheLav/iis-deploy@v1.1.1
        with:
          website-name: ESRC_Docs
          msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
          msdeploy-username: ${{ secrets.WEBSITE_USERNAME }}
          msdeploy-password: ${{ secrets.WEBSITE_PASSWORD }}
          source-path: ${{ github.workspace }}/build
          skip-extra-files: false
          extra-args: '-enableRule:DoNotDeleteRule -allowUntrusted'
