name: Deploy Docusaurus to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      TINA_BRANCH: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to IIS using WebDeploy
        uses: ChristopheLav/iis-deploy@v1.1.1
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}            # e.g., ESRC_Docs or Default Web Site
          msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}    # e.g., https://hq-esrc-srv:8172
          msdeploy-username: ${{ secrets.WEBSITE_USERNAME }}   # e.g., AMREF\Denis.Kiragu
          msdeploy-password: ${{ secrets.WEBSITE_PASSWORD }}
          source-path: build                                   # Deploy folder from your repo
          skip-extra-files: false                              # Optional: preserves extra files on server
